DOP-6938: small fixes found during offline docs builds (#20368)
### Tickets
DOP-6938
DOP-6939
DOP-6940

### Errors 
1.
/docs/cloud-manager/reference/api/service-accounts/project/create-one-service-account-in-one-project/

https://deploy-preview-20368--docs-on-nextjs.netlify.app/docs/cloud-manager/reference/api/service-accounts/project/create-one-service-account-in-one-project/

Error: Expected component `Cond` to be defined: you likely forgot to
import, pass, or provide it.
    It’s referenced in your code at `314:1-330:8`


2. /docs/manual/reference/read-concern-snapshot/

https://deploy-preview-20368--docs-on-nextjs.netlify.app/docs/manual/reference/read-concern-snapshot/
Error: Expected component `Class` to be defined: you likely forgot to
import, pass, or provide it.
It’s referenced in your code at `2:1-6:9`
Fixed link:

** cant see the fixes in the url of the netlify staging since its not
using the new conversion script

3. /docs/languages/python/pymongo-driver/current
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading
'backgroundColor')
Source
src/mdx-components/Banner/index.tsx (18:46) @ backgroundColor

> 16 | const bannerStyle = ({ variant }: { variant: keyof typeof
styleMapLight }) => css`
    17 |   ${baseBannerStyle}
   18 |   background-color: ${styleMapLight[variant].backgroundColor};
    19 |   color: ${styleMapLight[variant].color};
    20 |   border-color: ${styleMapLight[variant].borderColor};
    21 |   ::before {
Fixed link:
https://deploy-preview-20368--docs-on-nextjs.netlify.app/docs/languages/python/pymongo-driver/current