printJson actually doesn't work
in
  MongoDB shell version: 2.0.7-rc0 (winXP)
"printJson" causes:
  ReferenceError: printJson is not defined (shell eval):1
"printjson" works fine